name: SpatialPPIv2
channels:
  - conda-forge
  - nvidia
  - pkgs/main
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.15.3=hb03c661_0
  - aom=3.12.1=h7934f7d_0
  - attr=2.5.2=h39aace5_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - blas=1.0=mkl
  - brotlicffi=1.2.0.0=py311h7354ed3_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2026.01.04=py311h06a4308_0
  - cffi=2.0.0=py311h4eded50_1
  - charset-normalizer=3.4.4=py311h06a4308_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.1.115=h4f1e1d6_0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.1=hd92462c_3
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h24cb091_1
  - expat=2.7.4=h7354ed3_0
  - ffmpeg=4.2.2=h20bf706_0
  - fftw=3.3.10=nompi_h3b011a4_111
  - filelock=3.20.3=py311h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h2c49b7f_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=hf5b9546_0
  - fribidi=1.0.16=h9fb5f84_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gdk-pixbuf=2.44.4=hbd8e730_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.86.3=h617169b_0
  - glib-tools=2.86.3=h9fad118_0
  - glslang=16.2.0=h96af755_1
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.2=py311ha78e65c_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - gstreamer-orc=0.4.42=h82d0256_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - harfbuzz=10.4.0=h76408a6_0
  - icu=75.1=he02047a_0
  - idna=3.11=py311h06a4308_0
  - intel-gmmlib=22.9.0=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jack=1.9.22=hf4617a5_3
  - jinja2=3.1.6=py311h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - kernel-headers_linux-64=4.18.0=h3108a97_1
  - lame=3.100=hbd0596d_1
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.8.2=h3ec8f01_0
  - libass=0.17.4=h6f62b05_1
  - libavif=1.3.0=h3539ee5_0
  - libcap=2.77=h3ff7636_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.16.1.26=h3b4bcfc_0
  - libcurand=10.4.1.81=h1b6c897_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.125=hb03c661_1
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.5.0=he200343_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.3=h8b17d9a_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libltdl=2.4.3a=h5888daf_0
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=h46f56fc_2
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.6.1=h9f10d21_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.54=hee55ce4_0
  - librsvg=2.58.4=h49af25d_2
  - libsndfile=1.2.2=hc7d488a_2
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libsystemd0=259.1=h6569c3e_0
  - libtasn1=4.21.0=h27ab2c4_0
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.1=h029b1ac_0
  - libtool=2.5.4=h5888daf_0
  - libudev1=259.1=h6569c3e_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libva=2.23.0=he1eb515_0
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.6.0=h089d785_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h04c0eec_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py311h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.6.1=py311h06a4308_0
  - numpy=2.0.1=py311h08b1b3b_1
  - numpy-base=2.0.1=py311hf175353_1
  - ocl-icd=2.3.3=h47b2149_0
  - opencl-headers=2025.07.22=hfb20e49_0
  - openfst=1.8.4=h84d6215_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.1=h35e630c_1
  - optree=0.18.0=py311hdf67eae_0
  - packaging=25.0=py311h06a4308_1
  - pango=1.56.3=h861ebed_0
  - pcre2=10.46=hf426167_0
  - pillow=12.0.0=py311h3b88751_1
  - pip=26.0.1=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pulseaudio=17.0=haebf07f_3
  - pulseaudio-client=17.0=h9a6aba3_3
  - pulseaudio-daemon=17.0=h33dcb6b_3
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.23=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_1
  - python=3.11.14=h6fa692b_0
  - python_abi=3.11=2_cp311
  - pytorch=2.5.1=py3.11_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py311h591646f_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py311h06a4308_1
  - setuptools=80.10.2=py311h06a4308_0
  - shaderc=2025.5=h718be3e_1
  - soxr=0.1.3=h0b41bf4_3
  - spirv-tools=2026.1=hb700be7_0
  - sqlite=3.51.1=he0a8d7e_0
  - svt-av1=3.1.2=hecca717_0
  - sympy=1.14.0=py311h06a4308_1
  - sysroot_linux-64=2.28=h3108a97_1
  - tbb=2021.8.0=hdb19cb5_0
  - tesseract=5.2.0=hb0d2e87_3
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=2.5.1=py311_cu121
  - torchtriton=3.1.0=py311
  - torchvision=0.20.1=py311_cu121
  - typing-extensions=4.15.0=py311h06a4308_0
  - typing_extensions=4.15.0=py311h06a4308_0
  - tzdata=2025c=he532380_0
  - urllib3=2.6.3=py311h06a4308_0
  - wayland=1.24.0=hdac8c69_0
  - wayland-protocols=1.47=hd8ed1ab_0
  - wheel=0.46.3=py311h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - git
  - pip:
    - --find-links https://data.pyg.org/whl/torch-2.5.1+cu121.html
    - Cython==3.0.2
    - Markdown==3.10.2
    - Werkzeug==3.1.5
    - absl-py==2.4.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.3
    - aiosignal==1.4.0
    - attrs==25.4.0
    - biopandas==0.5.1
    - biopython==1.83
    - contourpy==1.3.3
    - cycler==0.12.1
    - fair-esm==2.0.0
    - fonttools==4.61.1
    - freesasa==2.2.0.post3
    - frozenlist==1.8.0
    - fsspec==2026.2.0
    - grpcio==1.78.0
    - hf-xet==1.2.0
    - huggingface_hub==0.36.2
    - joblib==1.5.3
    - kiwisolver==1.4.9
    - lightning==2.6.1
    - lightning-utilities==0.15.2
    - looseversion==1.1.2
    - matplotlib==3.8.3
    - mmtf-python==1.1.3
    - msgpack==1.1.2
    - multidict==6.7.1
    - numpy==1.26.4
    - pandas==3.0.0
    - git+https://github.com/yusuf1759/prodigy-cryst.git
    - propcache==0.4.1
    - protobuf==6.33.5
    - psutil==7.2.2
    - pyg-lib==0.4.0+pt25cu121
    - pyparsing==3.3.2
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==2.6.1
    - regex==2026.1.15
    - safetensors==0.7.0
    - scikit-learn==1.2.2
    - scipy==1.12.0
    - seaborn==0.13.2
    - sentencepiece==0.2.0
    - six==1.17.0
    - sympy==1.13.1
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - threadpoolctl==3.6.0
    - tokenizers==0.19.1
    - torch_cluster==1.6.3
    - torch_geometric==2.5.1
    - torch_scatter==2.1.2
    - torch_sparse==0.6.18
    - torch_spline_conv==1.2.2
    - torchmetrics==1.8.2
    - torchsummary==1.5.1
    - tqdm==4.67.3
    - transformers==4.40.2
    - yarl==1.22.0
